### ISSUE TITLE
Missing H5 user manual?

### ISSUE THREAD

**Issue by ThomasKaiser** [OrangePiLibra/OrangePi_H5SDK#1]
I might have overseen it but it seems H5 user manual is still missing? Can you provide the PDF and other available documentation as soon as possible please?

**Comment by BuddyZhang1** [comment]
Hi,
  I am writing user manual, and I will tell user how to use this SDK via README.md. Pls wait for a while.

**Good Luck**

**Comment by eperie** [comment]
Hi,

I guess Thomas Kaiser, among others,  was rather looking for the Allwinner H5 user manual, that is the H5 equivalent for the [Allwinner A64 User Manual](http://dl.linux-sunxi.org/A64/Allwinner%20A64%20User%20Manual%20v1.0.pdf) - my two cents.

Thanks in advance for providing it.

**Comment by ThomasKaiser** [comment]
> I am writing user manual, and I will tell user how to use this SDK via README.md

Trank you but it's only about Allwinner's SoC user manual first. We (Linux-sunxi community) need this to fully support H5 SoC upstream -- please compare with eg https://github.com/apritzel/u-boot/commits/h5

No one wants to remain at 3.10.65 and Allwinner's outdated u-boot but still documentation is missing. Are you able to share what you got from Allwinner? :)

**Comment by BuddyZhang1** [comment]
@ThomasKaiser 
 This is H5 Datasheet: https://github.com/OrangePiLibra/OrangePi_H5SDK/tree/master/Documentation/Hardware
We don't have full user manual of H5, and Allwinner doesn't release it. I will update new user manual of H5 after Allwinner release it.

**Comment by ThomasKaiser** [comment]
There it is (705 pages): https://transfer.sh/Jmt1l/allwinner-h5-datasheet-v1.0.pdf

Should be added to dl.linux-sunxi.org soon and then be linked from [H5 page](http://linux-sunxi.org/H5)

**Comment by BuddyZhang1** [comment]
@ThomasKaiser 
 Thanks you! I will add into H5 SDK.

**Good!**
