### ISSUE TITLE
Automatic core detection for buildscripts

### ISSUE THREAD

**Issue by bsvdoom** [OrangePiLibra/OrangePi_H5SDK#10]
Its not an issue, rather an idea.
I think we should add a variable to the build scripts to determine the number of cores for speeding up the build...

CORES=$((\`cat /proc/cpuinfo | grep processor | wc -l\` - 1))

**Comment by bsvdoom** [comment]
Also, I think I collected all the required packages for the buildscript.
It would be useful to display theese packages in the readme.
_(Or it could do automatic dependency install...)_

bsdtar mtools u-boot-tools pv bc sunxi-tools gcc automake make qemu

**Comment by BuddyZhang1** [comment]
@bsvdoom  
  Thanks for your advice! It will hep developer easily to build OrangePi. ^_^
  I write some scripts to prepare those tools.
  commit: 1948714531976abe4c237e303ef77f1b537def6e
  commit: c47ff80cefec5cbe07b46d066a7a3d02f1e04268

**Good Luck**

**Comment by bsvdoom** [comment]
Nice, also  lib32z1 and  lib32z1-dev required for running the 32bit library 
`scripts/pack/pctools/linux/fsbuild200/fsbuild`

**Comment by BuddyZhang1** [comment]
@bsvdoom 
 Thank you!  lib32z1 and lib32z1-dev will help to compile uboot base on VirtualBox.
 Nice way! 1529d49c3706982b291d5dd96cf529cd3001f2a4

**Good Luck**

**Comment by bsvdoom** [comment]
@BuddyZhang1 
Cool, `dosfstools` also needed for build_image.sh

**Comment by bsvdoom** [comment]
Mkay, [this](https://github.com/OrangePiLibra/OrangePi_H5SDK/pull/13) could work..
