### ISSUE TITLE
How to force Opi PC2 NIC to work in 100mb mode ?

### ISSUE THREAD

**Issue by znoxx** [OrangePiLibra/OrangePi_H5SDK#23]
Looks like my gigabit switch does not work with OPI PC2 in 1gb mode. It's a probable issue of switch, not the board (but other devices work flawlessly).
Anyway, what is the correct way to set eth0 to 100mbit mode ?

**Comment by BuddyZhang1** [comment]
@znoxx 
Hi, firends:
   patch to set 100mbit https://github.com/OrangePiLibra/OrangePi_H5SDK/tree/master/external/patch

**Comment by BuddyZhang1** [comment]
close
